let NINHO_USER={demo:true,name:"",id:null}, NINHO_FAMILY={id:null,invite:"",plan:"free",role:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let K="ninho-mobile-v3-guest"; const colors=["#b9cfb5","#e3b8a6","#b9c9d7","#d9c49a","#d1b8d5"];
const iso=(off=0)=>{let d=new Date();d.setDate(d.getDate()+off);const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`};
const canManage=()=>NINHO_FAMILY.role==="admin"||NINHO_FAMILY.role==="adult";
const esc=v=>String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
const emptyData=()=>({members:[],events:[],tasks:[],shopping:[]});
let data=emptyData(), cal=new Date();cal.setDate(1);
function useUserStorage(userId){K=`ninho-mobile-v3-${userId||"guest"}`;try{data=JSON.parse(localStorage.getItem(K)||"null")||emptyData()}catch{data=emptyData()}}
function ownerOnlyData(){const name=NINHO_USER.name||"Usuário";return {members:[{id:"self",name,initial:name[0].toUpperCase(),color:colors[0]}],events:[],tasks:[],shopping:[]}}
let save=()=>localStorage.setItem(K,JSON.stringify(data));const mem=id=>data.members.find(x=>x.id===id)||{name:id?"Membro removido":"Sem responsável",initial:"?",color:colors[0]};const av=m=>`<span class="avatar" style="background:${esc(m?.color||colors[0])}">${esc(m?.initial||"?")}</span>`;
$("#date").textContent=new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
function setView(v){$$(".view").forEach(x=>x.classList.toggle("active",x.id===v));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));render()}$$(".nav").forEach(x=>x.onclick=()=>setView(x.dataset.view));$$("[data-go]").forEach(x=>x.onclick=()=>setView(x.dataset.go));
function taskRow(t){let m=mem(t.member);const allowed=NINHO_FAMILY.role!=="child"||t.member===NINHO_USER.id;return `<div class="row"><button class="check ${t.done?"done":""}" ${allowed?`onclick="task('${t.id}')"`:`disabled aria-label="Somente o responsável pode concluir"`}>${t.done?"✓":""}</button><div><div class="row-title ${t.done?"strike":""}">${esc(t.title)}</div><div class="sub">${esc(m.name)}</div></div>${av(m)}${contentAction("task",t.id)}</div>`}
function render(){const limited=!canManage();$("#fab").classList.toggle("hide",limited);$("#quick").classList.toggle("hide",limited);$$("[data-add], [data-type]").forEach(b=>b.classList.toggle("hide",limited));let now=new Date(),current=now.toTimeString().slice(0,5);let upcoming=data.events.filter(e=>e.date>iso()||(e.date===iso()&&e.time>=current)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))[0];$("#nextEvent").innerHTML=upcoming?(()=>{let m=mem(upcoming.member),label=upcoming.date===iso()?"Hoje":upcoming.date===iso(1)?"Amanhã":new Date(upcoming.date+"T12:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"});return `<div class="next-card"><div><div class="time">${label} · ${upcoming.time}</div><h2>${esc(upcoming.title)}</h2><div class="who">${av(m)} ${esc(m.name)}</div></div><div class="big-icon">♡</div></div>`})():`<div class="next-card"><div><div class="time">TUDO LIVRE</div><h2>Nenhum compromisso próximo</h2></div><div class="big-icon">🌿</div></div>`;$("#todayTasks").innerHTML=data.tasks.filter(t=>!t.done).slice(0,3).map(taskRow).join("")||`<div class="empty">Tudo feito por hoje ✓</div>`;$("#taskList").innerHTML=data.tasks.map(taskRow).join("")||`<div class="empty">Nenhuma tarefa.</div>`;$("#shopList").innerHTML=data.shopping.map(x=>`<div class="row"><button class="check ${x.done?"done":""}" onclick="shop('${x.id}')">${x.done?"✓":""}</button><div class="row-title ${x.done?"strike":""}">${esc(x.title)}</div>${contentAction("shopping",x.id)}${canManage()?`<button class="delete" onclick="delShop('${x.id}')" aria-label="Excluir item">×</button>`:""}</div>`).join("")||`<div class="empty">Lista vazia.</div>`;$("#shopCount").textContent=`${data.shopping.filter(x=>!x.done).length} pendentes`;renderCal();renderEvents()}
window.task=async id=>{let x=data.tasks.find(t=>t.id===id);if(!x||NINHO_FAMILY.role==="child"&&x.member!==NINHO_USER.id)return;const before=x.done;x.done=!x.done;render();try{await NinhoCloud.setTaskDone(id,x.done)}catch(e){x.done=before;render();toast("Não foi possível atualizar")}};
window.shop=async id=>{let x=data.shopping.find(t=>t.id===id);if(!x)return;const before=x.done;x.done=!x.done;render();try{await NinhoCloud.setShoppingDone(id,x.done)}catch(e){x.done=before;render();toast("Não foi possível atualizar")}};
window.delShop=async id=>{if(!canManage())return;const old=[...data.shopping];data.shopping=data.shopping.filter(x=>x.id!==id);render();try{await NinhoCloud.deleteShopping(id)}catch(e){data.shopping=old;render();toast("Não foi possível excluir")}};
$("#quick").onsubmit=async e=>{e.preventDefault();if(!canManage())return;let v=$("#quickInput").value.trim();if(!v)return;const x={id:crypto.randomUUID(),title:v,done:false};data.shopping.unshift(x);$("#quickInput").value="";render();try{await NinhoCloud.addShopping(NINHO_FAMILY.id,x);toast("Adicionado ✓")}catch(err){data.shopping=data.shopping.filter(i=>i.id!==x.id);render();toast("Não foi possível adicionar")}};
function renderCal(){$("#month").textContent=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(cal);let y=cal.getFullYear(),m=cal.getMonth(),f=new Date(y,m,1),start=new Date(y,m,1-f.getDay()),h="";for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let di=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;h+=`<div class="day ${d.getMonth()!=m?"muted":""} ${di===iso()?"today":""} ${data.events.some(e=>e.date===di)?"has":""}">${d.getDate()}</div>`}$("#days").innerHTML=h}
function renderEvents(){const month=`${cal.getFullYear()}-${String(cal.getMonth()+1).padStart(2,"0")}`;let es=data.events.filter(e=>e.date.startsWith(month)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$("#eventList").innerHTML=es.map(e=>{let m=mem(e.member),d=new Date(e.date+"T12:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"short"});return `<div class="row"><div><b>${d}</b><div class="sub">${e.time}</div></div><div class="row-title">${esc(e.title)}</div>${av(m)}${contentAction("event",e.id)}</div>`}).join("")||`<div class="empty">Sem compromissos.</div>`}
$("#prev").onclick=()=>{cal.setMonth(cal.getMonth()-1);renderCal();renderEvents()};$("#next").onclick=()=>{cal.setMonth(cal.getMonth()+1);renderCal();renderEvents()};
const bg=$("#sheetBg"),form=$("#form"),choices=$("#choices");function open(type){if(!canManage())return;bg.classList.add("open");type?build(type):(choices.classList.remove("hide"),form.classList.add("hide"),$("#sheetTitle").textContent="Adicionar")}function close(){bg.classList.remove("open");form.innerHTML=""}$("#fab").onclick=()=>open();$("#close").onclick=close;bg.onclick=e=>{if(e.target===bg)close()};$$("[data-add]").forEach(b=>b.onclick=()=>open(b.dataset.add));$$("[data-type]").forEach(b=>b.onclick=()=>build(b.dataset.type));const opts=()=>data.members.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join("");
function build(t){choices.classList.add("hide");form.classList.remove("hide");form.dataset.type=t;let title={event:"Compromisso",task:"Tarefa",shopping:"Compra",reminder:"Lembrete",member:"Novo membro"}[t];$("#sheetTitle").textContent=title;if(t==="event"||t==="reminder")form.innerHTML=`<label>Título<input name="title" required placeholder="${t==="reminder"?"Ex.: Ligar para a vovó":"Ex.: Dentista"}"></label><label>Data<input name="date" type="date" value="${iso()}" required></label><label>Horário<input name="time" type="time" value="09:00" required></label><label>Para quem?<select name="member">${opts()}</select></label><button>Salvar</button>`;if(t==="task")form.innerHTML=`<label>Tarefa<input name="title" required placeholder="Ex.: Tirar o lixo"></label><label>Responsável<select name="member">${opts()}</select></label><button>Salvar</button>`;if(t==="shopping")form.innerHTML=`<label>Item<input name="title" required placeholder="Ex.: Leite"></label><button>Adicionar</button>`;if(t==="member")form.innerHTML=`<label>Nome<input name="name" required placeholder="Nome"></label><button>Adicionar</button>`}
form.onsubmit=async e=>{e.preventDefault();if(!canManage())return;let x=Object.fromEntries(new FormData(form)),id=crypto.randomUUID(),t=form.dataset.type,item={id,...x};try{if(t==="event"||t==="reminder"){data.events.push(item);await NinhoCloud.addEvent(NINHO_FAMILY.id,item)}if(t==="task"){item={id,title:x.title,member:x.member,done:false};data.tasks.push(item);await NinhoCloud.addTask(NINHO_FAMILY.id,item)}if(t==="shopping"){item={id,title:x.title,done:false};data.shopping.push(item);await NinhoCloud.addShopping(NINHO_FAMILY.id,item)}render();close();renderFamily();toast("Salvo no Ninho ✓")}catch(err){await refreshShared();toast(err.message||"Não foi possível salvar")}};
function toast(s){let t=$("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1600)}
const fbg=$("#familyBg");$("#profile").onclick=()=>{renderFamily();fbg.classList.add("open")};$("#closeFamily").onclick=()=>fbg.classList.remove("open");fbg.onclick=e=>{if(e.target===fbg)fbg.classList.remove("open")};function renderFamily(){const list=$("#familyList");if(!list)return;list.innerHTML=data.members.map(m=>`<div class="family-row">${av(m)}<div class="info"><b>${esc(m.name)}</b><span class="sub">Membro da família</span></div></div>`).join("")}
const legacyAddMember=$("#addMember");if(legacyAddMember)legacyAddMember.onclick=()=>{fbg.classList.remove("open");$("#inviteSettingsBtn").click()};if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("sw.js").catch(()=>{});render();
const authScreen=$("#authScreen"),verifyEmailScreen=$("#verifyEmailScreen"),resetPasswordScreen=$("#resetPasswordScreen"),onboarding=$("#onboarding");let pendingVerificationEmail="",authMode="login";$$("[data-auth]").forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;$$("[data-auth]").forEach(x=>x.classList.toggle("active",x===b));$("#nameField").classList.toggle("hide",authMode!=="signup");$("#authSubmit").textContent=authMode==="login"?"Entrar":"Criar conta"});$("#demoBtn").classList.add("hide");let authBusy=false;
$("#authForm").onsubmit=async e=>{e.preventDefault();if(authBusy)return;const submitBtn=$("#authSubmit"),originalText=submitBtn.textContent;authBusy=true;submitBtn.disabled=true;submitBtn.textContent=authMode==="signup"?"Criando conta...":"Entrando...";try{let email=$("#authEmail").value.trim(),password=$("#authPassword").value;let res=authMode==="signup"?await NinhoCloud.signUp(email,password,$("#authName").value.trim()):await NinhoCloud.signIn(email,password);if(authMode==="signup"&&!res.data.session){pendingVerificationEmail=email;$("#verifyEmailAddress").textContent=email;authScreen.classList.add("hide");verifyEmailScreen.classList.remove("hide");return}const p=await NinhoCloud.profile();NINHO_USER={demo:false,id:p?.id||null,name:p?.name||email.split("@")[0],email:p?.email||email,phone:p?.phone||""};authScreen.classList.add("hide");await bootCloud()}catch(err){const msg=(err?.message||"").toLowerCase();if(msg.includes("email not confirmed")||msg.includes("email_not_confirmed")){pendingVerificationEmail=$("#authEmail").value.trim();$("#verifyEmailAddress").textContent=pendingVerificationEmail;authScreen.classList.add("hide");verifyEmailScreen.classList.remove("hide");$("#verifyStatus").textContent="Seu e-mail ainda não foi confirmado. Abra o link enviado ou reenvie abaixo."}else if(err?.status===429||err?.code==="over_email_send_rate_limit"||msg.includes("rate limit")||msg.includes("too many"))toast("Muitas tentativas em pouco tempo. Aguarde alguns minutos e tente novamente.");else toast(err.message||"Não foi possível entrar")}finally{authBusy=false;submitBtn.disabled=false;submitBtn.textContent=authMode==="login"?"Entrar":"Criar conta"}};
let forgotBusy=false;$("#forgotPassword").onclick=async()=>{if(forgotBusy)return;const email=$("#authEmail").value.trim(),btn=$("#forgotPassword"),status=$("#forgotStatus");status.classList.remove("hide");if(!email){status.textContent="Informe seu e-mail acima para receber o link de recuperação.";$("#authEmail").focus();return}forgotBusy=true;btn.disabled=true;btn.textContent="Enviando...";status.textContent="Solicitando link de recuperação...";try{await NinhoCloud.requestPasswordReset(email);status.classList.add("hide");$("#recoveryEmail").textContent=email;$("#recoverySent").classList.remove("hide");$("#authForm").classList.add("hide");$("#forgotPassword").classList.add("hide");toast("E-mail de recuperação enviado ✓")}catch(err){const msg=(err?.message||"").toLowerCase();if(err?.status===429||err?.code==="over_email_send_rate_limit"||msg.includes("rate limit")||msg.includes("too many"))status.textContent="Muitas tentativas em pouco tempo. Aguarde alguns minutos e tente novamente.";else status.textContent=err?.message||"Não foi possível enviar o link de recuperação.";toast("Não foi possível enviar o link")}finally{forgotBusy=false;btn.disabled=false;btn.textContent="Esqueci minha senha"}};
$("#recoveryBack").onclick=()=>{$("#recoverySent").classList.add("hide");$("#authForm").classList.remove("hide");$("#forgotPassword").classList.remove("hide");$("#forgotStatus").classList.add("hide");};
NinhoCloud.onAuthChange((event)=>{if(event==="PASSWORD_RECOVERY"){authScreen.classList.add("hide");verifyEmailScreen.classList.add("hide");resetPasswordScreen.classList.remove("hide")}});
$("#resetPasswordForm").onsubmit=async e=>{e.preventDefault();try{await NinhoCloud.updatePassword($("#newPassword").value);resetPasswordScreen.classList.add("hide");toast("Senha atualizada ✓");history.replaceState({},document.title,location.pathname);const p=await NinhoCloud.profile();NINHO_USER={demo:false,id:p?.id||null,name:p?.name||"Família",email:p?.email||"",phone:p?.phone||""};await bootCloud()}catch(err){toast(err.message||"Não foi possível atualizar a senha")}};
$("#resendVerification").onclick=async()=>{try{if(!pendingVerificationEmail)return toast("Informe seu e-mail novamente");const btn=$("#resendVerification");btn.disabled=true;btn.textContent="Enviando...";await NinhoCloud.resendConfirmation(pendingVerificationEmail);$("#verifyStatus").textContent="Novo e-mail enviado ✓ Confira sua caixa de entrada e o spam.";toast("E-mail de confirmação reenviado ✓");setTimeout(()=>{btn.disabled=false;btn.textContent="Reenviar e-mail"},3000)}catch(err){const btn=$("#resendVerification"),msg=(err?.message||"").toLowerCase();if(err?.status===429||err?.code==="over_email_send_rate_limit"||msg.includes("rate limit")||msg.includes("too many")){$("#verifyStatus").textContent="Limite temporário de e-mails atingido. Aguarde alguns minutos antes de reenviar.";toast("Aguarde antes de solicitar outro e-mail.");setTimeout(()=>{btn.disabled=false;btn.textContent="Reenviar e-mail"},60000)}else{btn.disabled=false;btn.textContent="Reenviar e-mail";toast(err.message||"Não foi possível reenviar")}}};
$("#backToLogin").onclick=()=>{verifyEmailScreen.classList.add("hide");authScreen.classList.remove("hide");authMode="login";$$('[data-auth]').forEach(x=>x.classList.toggle('active',x.dataset.auth==='login'));$("#nameField").classList.add("hide");$("#authSubmit").textContent="Entrar"};
async function refreshShared(){if(!NINHO_FAMILY.id)return;const shared=await NinhoCloud.loadShared(NINHO_FAMILY.id);data={...data,...shared};localStorage.setItem(K,JSON.stringify(data));render()}
async function refreshMembership(){const f=await NinhoCloud.loadFamily();if(!f||f.family_id!==NINHO_FAMILY.id){await bootCloud();return}NINHO_FAMILY.role=f.role;data.members=await NinhoCloud.familyMembers();localStorage.setItem(K,JSON.stringify(data));render();refreshSettings()}
async function bootCloud(){const u=await NinhoCloud.user();useUserStorage(u?.id);let f=await NinhoCloud.loadFamily();if(!f){NINHO_FAMILY={id:null,invite:"",plan:"free",role:null};data=emptyData();localStorage.setItem(K,JSON.stringify(data));render();onboarding.classList.remove("hide");return}NINHO_FAMILY={id:f.family_id,invite:f.invite_code,plan:f.plan,role:f.role};data=emptyData();const realMembers=await NinhoCloud.familyMembers();if(realMembers.length)data.members=realMembers;await refreshShared();NinhoCloud.realtime(NINHO_FAMILY.id,async()=>{await refreshShared();toast("Família atualizada")},refreshMembership)}
$("#createFamily").onclick=async()=>{if(!NinhoCloud.enabled)return toast("Conecte a nuvem primeiro");try{let f=await NinhoCloud.createFamily("Minha família");NINHO_FAMILY={id:f.family_id,invite:f.invite_code,plan:"free",role:"admin"};onboarding.classList.add("hide");data=ownerOnlyData();const realMembers=await NinhoCloud.familyMembers();if(realMembers.length)data.members=realMembers;localStorage.setItem(K,JSON.stringify(data));render();await refreshShared();NinhoCloud.realtime(NINHO_FAMILY.id,refreshShared,refreshMembership);toast("Família criada ✓")}catch(e){toast(e.message)}};$("#joinForm").onsubmit=async e=>{e.preventDefault();try{await NinhoCloud.joinFamily($("#inviteCode").value);onboarding.classList.add("hide");await bootCloud();toast("Você entrou na família ✓")}catch(x){toast(x.message||"Código inválido")}};
const localSave=save;save=()=>localSave();const legacyCopyInvite=$("#copyInvite");if(legacyCopyInvite)legacyCopyInvite.onclick=async()=>{await navigator.clipboard?.writeText(NINHO_FAMILY.invite);toast("Código copiado: "+NINHO_FAMILY.invite)};$("#logoutBtn").onclick=async()=>{await NinhoCloud.signOut();location.reload()};
const pbg=$("#premiumBg"),legacyPremiumBtn=$("#premiumBtn");if(legacyPremiumBtn)legacyPremiumBtn.onclick=()=>pbg.classList.add("open");const closePremiumBtn=$("#closePremium");if(closePremiumBtn)closePremiumBtn.onclick=()=>pbg.classList.remove("open");if(pbg)pbg.onclick=e=>{if(e.target===pbg)pbg.classList.remove("open")};const subscribeBtn=$("#subscribeBtn");if(subscribeBtn)subscribeBtn.onclick=()=>toast("Ninho+ está em desenvolvimento — nenhuma cobrança é realizada");
(async()=>{if(!NinhoCloud.enabled)return;try{const s=await NinhoCloud.session();if(s){const p=await NinhoCloud.profile();NINHO_USER={demo:false,id:p?.id||s.user.id,name:p?.name||s.user.user_metadata?.name||"Família",email:p?.email||s.user.email,phone:p?.phone||""};authScreen.classList.add("hide");verifyEmailScreen.classList.add("hide");await bootCloud();if(location.hash.includes("access_token")||location.search.includes("code="))toast("E-mail confirmado ✓")}}catch(e){console.error(e)}})();
const detailBg=$("#detailBg");function openDetail(title,content){$("#detailTitle").textContent=title;$("#detailContent").innerHTML=content;detailBg.classList.add("open")}$("#closeDetail").onclick=()=>detailBg.classList.remove("open");detailBg.onclick=e=>{if(e.target===detailBg)detailBg.classList.remove("open")};
function refreshSettings(){const me=data.members[0]||{name:NINHO_USER.name||"Usuário",initial:"U"};$("#settingsName").textContent=NINHO_USER.name||me.name;$("#settingsAvatar").textContent=(NINHO_USER.name||me.name||"U")[0].toUpperCase();$("#settingsEmail").textContent=NINHO_USER.email||"Conta conectada";$("#leaveFamilyBtn").classList.toggle("hide",NINHO_FAMILY.role==="admin");$("#inviteSettingsBtn").classList.toggle("hide",NINHO_FAMILY.role==="child");$("#memberCountLabel").textContent=`${data.members.length} ${data.members.length===1?"membro":"membros"}`;$("#inviteSmall").textContent="Código "+(NINHO_FAMILY.invite||"—");$("#planName").textContent=NINHO_FAMILY.plan==="plus"?"Ninho+":"Ninho gratuito";$("#planStatus").textContent=NINHO_FAMILY.plan==="plus"?"Assinatura ativa":"Conheça os recursos do Ninho+"}
$("#profile").onclick=()=>{refreshSettings();fbg.classList.add("open")};
$("#personalDataBtn").onclick=async()=>{let p=await NinhoCloud.profile();openDetail("Dados pessoais",`<form class="detail-form" id="profileForm"><label>Nome<input name="name" value="${esc(p?.name||NINHO_USER.name||"")}" required></label><label>E-mail<input name="email" type="email" value="${esc(p?.email||NINHO_USER.email||"")}" required></label><label>Telefone<input name="phone" type="tel" value="${esc(p?.phone||"")}" placeholder="(11) 99999-9999"></label><button class="full">Salvar alterações</button></form>`);$("#profileForm").onsubmit=async e=>{e.preventDefault();try{let x=Object.fromEntries(new FormData(e.target));let updated=await NinhoCloud.updateProfile(x);NINHO_USER={...NINHO_USER,...updated};refreshSettings();detailBg.classList.remove("open");toast(x.email!==p.email?"Dados salvos. Novo e-mail pode precisar de confirmação.":"Dados atualizados ✓")}catch(err){toast(err.message||"Erro ao salvar")}}};
$("#editProfileBtn").onclick=()=>$("#personalDataBtn").click();$("#membersBtn").onclick=()=>{const admin=NINHO_FAMILY.role==="admin";openDetail("Membros da família",data.members.map(m=>`<div class="member-manage">${av(m)}<div><b>${esc(m.name)}</b><small>${m.role==="admin"?"Administrador":m.role==="child"?"Criança":"Adulto"}</small></div>${admin&&m.role!=="admin"?`<select class="member-role" data-member="${esc(m.id)}"><option value="adult" ${m.role==="adult"?"selected":""}>Adulto</option><option value="child" ${m.role==="child"?"selected":""}>Criança</option></select><button class="member-transfer" data-member="${esc(m.id)}" data-name="${esc(m.name)}" aria-label="Transferir administração">★</button><button class="delete member-remove" data-member="${esc(m.id)}" aria-label="Remover membro">×</button>`:""}</div>`).join("")+(admin?`<button class="full" id="detailAddMember">＋ Adicionar membro</button>`:""))};$("#inviteSettingsBtn").onclick=()=>{if(NINHO_FAMILY.role==="child")return;openDetail("Convidar para a família",`<div class="invite-box"><div>Compartilhe este código</div><div class="invite-code">${NINHO_FAMILY.invite||"—"}</div><small>O familiar cria uma conta e usa o código para entrar no seu Ninho.</small></div><button class="full" id="copyInviteDetail">Copiar código</button>`)};
$("#subscriptionBtn").onclick=()=>{if(NINHO_FAMILY.plan==="plus")openDetail("Minha assinatura",`<div class="sub-card"><small>PLANO ATUAL</small><h3>💎 Ninho+</h3><p>R$ 12,90/mês · assinatura familiar</p><b>Ativa</b></div><button class="cancel-btn" id="cancelSub">Cancelar assinatura</button>`);else{fbg.classList.remove("open");pbg.classList.add("open")}};
$("#leaveFamilyBtn").onclick=()=>openDetail("Sair da família",`<div class="confirm-box"><p>Ao sair desta família, você deixará de ver a agenda, tarefas e listas compartilhadas. Sua conta continuará existindo.</p><div class="confirm-actions"><button class="safe" id="stayFamily">Ficar</button><button class="danger" id="confirmLeave">Sair da família</button></div></div>`);
const notificationKey=()=>K+"-notifications";
const notificationPrefs=()=>{try{return JSON.parse(localStorage.getItem(notificationKey())||"null")||{reminders:true,family:true}}catch{return {reminders:true,family:true}}};
$("#notificationsBtn").onclick=()=>{const p=notificationPrefs();openDetail("Notificações",`<div class="member-manage"><div>🔔</div><div><b>Lembretes</b><small>Compromissos e tarefas atribuídas a você</small></div><input id="notifReminders" type="checkbox" ${p.reminders?"checked":""}></div><div class="member-manage"><div>🏡</div><div><b>Atividade da família</b><small>Avisos importantes do Ninho</small></div><input id="notifFamily" type="checkbox" ${p.family?"checked":""}></div>`)};
$("#helpBtn").onclick=()=>openDetail("Ajuda e suporte","<div class=\"confirm-box\"><p><b>Adicionar itens:</b> use o botão + para criar compromissos, tarefas e compras.</p><p><b>Agenda:</b> use as setas para navegar pelos meses e editar compromissos.</p><p><b>Família:</b> em Configurações, Admins gerenciam membros e papéis. Adultos gerenciam conteúdo compartilhado. Crianças têm ações limitadas ao próprio uso.</p><p><b>Sincronização:</b> alterações da família são atualizadas pela nuvem quando há conexão.</p></div>");
$("#privacyBtn").onclick=()=>openDetail("Privacidade e segurança","<div class=\"confirm-box\"><p>Os dados do Ninho ficam associados à sua conta e à família conectada no Supabase.</p><p>O acesso ao conteúdo compartilhado é controlado por papéis de <b>Administrador</b>, <b>Adulto</b> e <b>Criança</b>. Crianças não recebem o código de convite da família.</p><p>Ao sair da conta, a sessão local é encerrada. Ao sair de uma família, o acesso aos dados compartilhados dessa família é removido.</p><p>Esta tela resume os controles técnicos atuais do aplicativo.</p><p><a href='privacy.html' target='_blank' rel='noopener'>Ler política de privacidade completa</a></p></div>");
detailBg.addEventListener("change",async e=>{if(e.target.classList.contains("member-role")){try{await NinhoCloud.setMemberRole(e.target.dataset.member,e.target.value);data.members=await NinhoCloud.familyMembers();$("#membersBtn").click();toast("Papel atualizado ✓")}catch(err){toast(err.message||"Não foi possível alterar")}}if(e.target.id==="notifReminders"||e.target.id==="notifFamily"){const p=notificationPrefs();if(e.target.id==="notifReminders")p.reminders=e.target.checked;else p.family=e.target.checked;localStorage.setItem(notificationKey(),JSON.stringify(p));toast("Preferência salva ✓")}});
detailBg.addEventListener("click",async e=>{if(e.target.classList.contains("member-transfer")){const name=e.target.dataset.name||"este membro";if(confirm(`Transferir a administração da família para ${name}? Você passará a ser Adulto.`)){try{await NinhoCloud.transferAdmin(e.target.dataset.member);NINHO_FAMILY.role="adult";data.members=await NinhoCloud.familyMembers();$("#membersBtn").click();refreshSettings();toast("Administração transferida ✓")}catch(err){toast(err.message||"Não foi possível transferir")}}}if(e.target.classList.contains("member-remove")){try{await NinhoCloud.removeMember(e.target.dataset.member);data.members=await NinhoCloud.familyMembers();$("#membersBtn").click();toast("Membro removido ✓")}catch(err){toast(err.message||"Não foi possível remover")}}if(e.target.id==="copyInviteDetail"){await navigator.clipboard?.writeText(NINHO_FAMILY.invite||"");toast("Código copiado ✓")}if(e.target.id==="detailAddMember"){detailBg.classList.remove("open");fbg.classList.remove("open");$("#inviteSettingsBtn").click()}if(e.target.id==="stayFamily")detailBg.classList.remove("open");if(e.target.id==="confirmLeave"){try{await NinhoCloud.leaveFamily();detailBg.classList.remove("open");fbg.classList.remove("open");NINHO_FAMILY={id:null,invite:"",plan:"free",role:null};data=emptyData();localStorage.setItem(K,JSON.stringify(data));render();onboarding.classList.remove("hide");toast("Você saiu da família")}catch(err){toast(err.message||"Não foi possível sair da família")}}if(e.target.id==="cancelSub")openDetail("Cancelar Ninho+",`<div class="confirm-box"><p>Seu Ninho+ continuará ativo até o fim do período já pago. Depois, sua família volta ao plano gratuito.</p><div class="confirm-actions"><button class="safe" id="staySub">Manter Ninho+</button><button class="danger" id="confirmCancel">Cancelar</button></div></div>`);if(e.target.id==="staySub")detailBg.classList.remove("open");if(e.target.id==="confirmCancel"){NINHO_FAMILY.plan="free";detailBg.classList.remove("open");toast("Cancelamento preparado para o sistema de cobrança")}});

window.addEventListener("focus",async()=>{if(!NINHO_FAMILY.id||NINHO_USER.demo)return;try{await refreshMembership()}catch(e){console.warn("Falha ao atualizar membros",e)}});

function contentAction(kind,id){return canManage()?`<button class="delete" onclick="manageContent('${kind}','${id}')" aria-label="Editar ${kind==="task"?"tarefa":kind==="event"?"compromisso":"compra"}">✎</button>`:""}
window.manageContent=(kind,id)=>{
 if(!canManage())return;
 const collection={task:"tasks",event:"events",shopping:"shopping"}[kind],item=data[collection]?.find(x=>x.id===id);
 if(!item)return;
 const label={task:"tarefa",event:"compromisso",shopping:"compra"}[kind];
 openDetail("Editar "+label,`<form class="detail-form" id="contentEditForm"><label>Título<input name="title" required value="${esc(item.title)}"></label>${kind==="event"?`<label>Data<input name="date" type="date" required value="${esc(item.date)}"></label><label>Horário<input name="time" type="time" required value="${esc(item.time)}"></label>`:""}${kind!=="shopping"?`<label>Responsável<select name="member"><option value="">Sem responsável</option>${opts()}</select></label>`:""}<button type="submit">Salvar alterações</button><button type="button" class="cancel-btn" id="deleteContentBtn">Excluir ${label}</button></form>`);
 const editor=$("#contentEditForm");
 if(editor.elements.member)editor.elements.member.value=item.member||"";
 let busy=false;
 const run=async action=>{if(busy||!canManage())return;busy=true;editor.querySelectorAll("button").forEach(b=>b.disabled=true);try{await action();await refreshShared();detailBg.classList.remove("open");toast("Alteração salva ✓")}catch(err){toast(err.message||"Não foi possível salvar")}finally{busy=false;editor.querySelectorAll("button").forEach(b=>b.disabled=false)}};
 editor.onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(editor));values.title=values.title.trim();if(!values.title)return toast("Informe um título");run(()=>NinhoCloud.updateContent(kind,id,values))};
 $("#deleteContentBtn").onclick=()=>{if(confirm("Excluir este item?"))run(()=>NinhoCloud.deleteContent(kind,id))};
};
