let NINHO_USER={demo:true,name:""}, NINHO_FAMILY={id:null,invite:"",plan:"free"};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let K="ninho-mobile-v3-guest"; const colors=["#b9cfb5","#e3b8a6","#b9c9d7","#d9c49a","#d1b8d5"];
const iso=(off=0)=>{let d=new Date();d.setDate(d.getDate()+off);return d.toISOString().slice(0,10)};
const emptyData=()=>({members:[],events:[],tasks:[],shopping:[]});
let data=emptyData(), cal=new Date();cal.setDate(1);
function useUserStorage(userId){K=`ninho-mobile-v3-${userId||"guest"}`;try{data=JSON.parse(localStorage.getItem(K)||"null")||emptyData()}catch{data=emptyData()}}
function ownerOnlyData(){const name=NINHO_USER.name||"Usuário";return {members:[{id:"self",name,initial:name[0].toUpperCase(),color:colors[0]}],events:[],tasks:[],shopping:[]}}
let save=()=>localStorage.setItem(K,JSON.stringify(data));const mem=id=>data.members.find(x=>x.id===id)||data.members[0];const av=m=>`<span class="avatar" style="background:${m.color}">${m.initial}</span>`;
$("#date").textContent=new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
function setView(v){$$(".view").forEach(x=>x.classList.toggle("active",x.id===v));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));render()}$$(".nav").forEach(x=>x.onclick=()=>setView(x.dataset.view));$$("[data-go]").forEach(x=>x.onclick=()=>setView(x.dataset.go));
function taskRow(t){let m=mem(t.member);return `<div class="row"><button class="check ${t.done?"done":""}" onclick="task('${t.id}')">${t.done?"✓":""}</button><div><div class="row-title ${t.done?"strike":""}">${t.title}</div><div class="sub">${m.name}</div></div>${av(m)}</div>`}
function render(){let now=new Date(),current=now.toTimeString().slice(0,5);let upcoming=data.events.filter(e=>e.date>iso()||(e.date===iso()&&e.time>=current)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))[0];$("#nextEvent").innerHTML=upcoming?(()=>{let m=mem(upcoming.member),label=upcoming.date===iso()?"Hoje":upcoming.date===iso(1)?"Amanhã":new Date(upcoming.date+"T12:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"});return `<div class="next-card"><div><div class="time">${label} · ${upcoming.time}</div><h2>${upcoming.title}</h2><div class="who">${av(m)} ${m.name}</div></div><div class="big-icon">♡</div></div>`})():`<div class="next-card"><div><div class="time">TUDO LIVRE</div><h2>Nenhum compromisso próximo</h2></div><div class="big-icon">🌿</div></div>`;$("#todayTasks").innerHTML=data.tasks.filter(t=>!t.done).slice(0,3).map(taskRow).join("")||`<div class="empty">Tudo feito por hoje ✓</div>`;$("#taskList").innerHTML=data.tasks.map(taskRow).join("")||`<div class="empty">Nenhuma tarefa.</div>`;$("#shopList").innerHTML=data.shopping.map(x=>`<div class="row"><button class="check ${x.done?"done":""}" onclick="shop('${x.id}')">${x.done?"✓":""}</button><div class="row-title ${x.done?"strike":""}">${x.title}</div><button class="delete" onclick="delShop('${x.id}')">×</button></div>`).join("")||`<div class="empty">Lista vazia.</div>`;$("#shopCount").textContent=`${data.shopping.filter(x=>!x.done).length} pendentes`;renderCal();renderEvents()}
window.task=id=>{let x=data.tasks.find(t=>t.id===id);x.done=!x.done;save();render()};window.shop=id=>{let x=data.shopping.find(t=>t.id===id);x.done=!x.done;save();render()};window.delShop=id=>{data.shopping=data.shopping.filter(x=>x.id!==id);save();render()};
$("#quick").onsubmit=e=>{e.preventDefault();let v=$("#quickInput").value.trim();if(!v)return;data.shopping.unshift({id:crypto.randomUUID(),title:v,done:false});$("#quickInput").value="";save();render();toast("Adicionado ✓")};
function renderCal(){$("#month").textContent=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(cal);let y=cal.getFullYear(),m=cal.getMonth(),f=new Date(y,m,1),start=new Date(y,m,1-f.getDay()),h="";for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let di=d.toISOString().slice(0,10);h+=`<div class="day ${d.getMonth()!=m?"muted":""} ${di===iso()?"today":""} ${data.events.some(e=>e.date===di)?"has":""}">${d.getDate()}</div>`}$("#days").innerHTML=h}
function renderEvents(){let es=data.events.filter(e=>e.date>=iso()).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,8);$("#eventList").innerHTML=es.map(e=>{let m=mem(e.member),d=new Date(e.date+"T12:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"short"});return `<div class="row"><div><b>${d}</b><div class="sub">${e.time}</div></div><div class="row-title">${e.title}</div>${av(m)}</div>`}).join("")||`<div class="empty">Sem compromissos.</div>`}
$("#prev").onclick=()=>{cal.setMonth(cal.getMonth()-1);renderCal()};$("#next").onclick=()=>{cal.setMonth(cal.getMonth()+1);renderCal()};
const bg=$("#sheetBg"),form=$("#form"),choices=$("#choices");function open(type){bg.classList.add("open");type?build(type):(choices.classList.remove("hide"),form.classList.add("hide"),$("#sheetTitle").textContent="Adicionar")}function close(){bg.classList.remove("open");form.innerHTML=""}$("#fab").onclick=()=>open();$("#close").onclick=close;bg.onclick=e=>{if(e.target===bg)close()};$$("[data-add]").forEach(b=>b.onclick=()=>open(b.dataset.add));$$("[data-type]").forEach(b=>b.onclick=()=>build(b.dataset.type));const opts=()=>data.members.map(m=>`<option value="${m.id}">${m.name}</option>`).join("");
function build(t){choices.classList.add("hide");form.classList.remove("hide");form.dataset.type=t;let title={event:"Compromisso",task:"Tarefa",shopping:"Compra",reminder:"Lembrete",member:"Novo membro"}[t];$("#sheetTitle").textContent=title;if(t==="event"||t==="reminder")form.innerHTML=`<label>Título<input name="title" required placeholder="${t==="reminder"?"Ex.: Ligar para a vovó":"Ex.: Dentista"}"></label><label>Data<input name="date" type="date" value="${iso()}" required></label><label>Horário<input name="time" type="time" value="09:00" required></label><label>Para quem?<select name="member">${opts()}</select></label><button>Salvar</button>`;if(t==="task")form.innerHTML=`<label>Tarefa<input name="title" required placeholder="Ex.: Tirar o lixo"></label><label>Responsável<select name="member">${opts()}</select></label><button>Salvar</button>`;if(t==="shopping")form.innerHTML=`<label>Item<input name="title" required placeholder="Ex.: Leite"></label><button>Adicionar</button>`;if(t==="member")form.innerHTML=`<label>Nome<input name="name" required placeholder="Nome"></label><button>Adicionar</button>`}
form.onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(form)),id=crypto.randomUUID(),t=form.dataset.type;if(t==="event"||t==="reminder")data.events.push({id,...x});if(t==="task")data.tasks.push({id,title:x.title,member:x.member,done:false});if(t==="shopping")data.shopping.push({id,title:x.title,done:false});if(t==="member")data.members.push({id,name:x.name,initial:x.name[0].toUpperCase(),color:colors[data.members.length%colors.length]});save();render();close();renderFamily();toast("Salvo no Ninho ✓")};
function toast(s){let t=$("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1600)}
const fbg=$("#familyBg");$("#profile").onclick=()=>{renderFamily();fbg.classList.add("open")};$("#closeFamily").onclick=()=>fbg.classList.remove("open");fbg.onclick=e=>{if(e.target===fbg)fbg.classList.remove("open")};function renderFamily(){const list=$("#familyList");if(!list)return;list.innerHTML=data.members.map(m=>`<div class="family-row">${av(m)}<div class="info"><b>${m.name}</b><span class="sub">Membro da família</span></div></div>`).join("")}
const legacyAddMember=$("#addMember");if(legacyAddMember)legacyAddMember.onclick=()=>{fbg.classList.remove("open");open("member")};if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("sw.js").catch(()=>{});render();
const authScreen=$("#authScreen"),verifyEmailScreen=$("#verifyEmailScreen"),onboarding=$("#onboarding");let pendingVerificationEmail="",authMode="login";$$("[data-auth]").forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;$$("[data-auth]").forEach(x=>x.classList.toggle("active",x===b));$("#nameField").classList.toggle("hide",authMode!=="signup");$("#authSubmit").textContent=authMode==="login"?"Entrar":"Criar conta"});$("#demoBtn").classList.add("hide");let authBusy=false;
$("#authForm").onsubmit=async e=>{e.preventDefault();if(authBusy)return;const submitBtn=$("#authSubmit"),originalText=submitBtn.textContent;authBusy=true;submitBtn.disabled=true;submitBtn.textContent=authMode==="signup"?"Criando conta...":"Entrando...";try{let email=$("#authEmail").value.trim(),password=$("#authPassword").value;let res=authMode==="signup"?await NinhoCloud.signUp(email,password,$("#authName").value.trim()):await NinhoCloud.signIn(email,password);if(authMode==="signup"&&!res.data.session){pendingVerificationEmail=email;$("#verifyEmailAddress").textContent=email;authScreen.classList.add("hide");verifyEmailScreen.classList.remove("hide");return}const p=await NinhoCloud.profile();NINHO_USER={demo:false,name:p?.name||email.split("@")[0],email:p?.email||email,phone:p?.phone||""};authScreen.classList.add("hide");await bootCloud()}catch(err){const msg=(err?.message||"").toLowerCase();if(msg.includes("email not confirmed")||msg.includes("email_not_confirmed")){pendingVerificationEmail=$("#authEmail").value.trim();$("#verifyEmailAddress").textContent=pendingVerificationEmail;authScreen.classList.add("hide");verifyEmailScreen.classList.remove("hide");$("#verifyStatus").textContent="Seu e-mail ainda não foi confirmado. Abra o link enviado ou reenvie abaixo."}else if(err?.status===429||err?.code==="over_email_send_rate_limit"||msg.includes("rate limit")||msg.includes("too many"))toast("Muitas tentativas em pouco tempo. Aguarde alguns minutos e tente novamente.");else toast(err.message||"Não foi possível entrar")}finally{authBusy=false;submitBtn.disabled=false;submitBtn.textContent=authMode==="login"?"Entrar":"Criar conta"}};
$("#resendVerification").onclick=async()=>{try{if(!pendingVerificationEmail)return toast("Informe seu e-mail novamente");const btn=$("#resendVerification");btn.disabled=true;btn.textContent="Enviando...";await NinhoCloud.resendConfirmation(pendingVerificationEmail);$("#verifyStatus").textContent="Novo e-mail enviado ✓ Confira sua caixa de entrada e o spam.";toast("E-mail de confirmação reenviado ✓");setTimeout(()=>{btn.disabled=false;btn.textContent="Reenviar e-mail"},3000)}catch(err){const btn=$("#resendVerification"),msg=(err?.message||"").toLowerCase();if(err?.status===429||err?.code==="over_email_send_rate_limit"||msg.includes("rate limit")||msg.includes("too many")){$("#verifyStatus").textContent="Limite temporário de e-mails atingido. Aguarde alguns minutos antes de reenviar.";toast("Aguarde antes de solicitar outro e-mail.");setTimeout(()=>{btn.disabled=false;btn.textContent="Reenviar e-mail"},60000)}else{btn.disabled=false;btn.textContent="Reenviar e-mail";toast(err.message||"Não foi possível reenviar")}}};
$("#backToLogin").onclick=()=>{verifyEmailScreen.classList.add("hide");authScreen.classList.remove("hide");authMode="login";$$('[data-auth]').forEach(x=>x.classList.toggle('active',x.dataset.auth==='login'));$("#nameField").classList.add("hide");$("#authSubmit").textContent="Entrar"};
async function bootCloud(){const u=await NinhoCloud.user();useUserStorage(u?.id);let f=await NinhoCloud.loadFamily();if(!f){onboarding.classList.remove("hide");return}NINHO_FAMILY={id:f.family_id,invite:f.invite_code,plan:f.plan};if(f.payload){data=f.payload;localStorage.setItem(K,JSON.stringify(data));render()}else{data=ownerOnlyData();localStorage.setItem(K,JSON.stringify(data));render()}NinhoCloud.realtime(NINHO_FAMILY.id,p=>{if(p){data=p;save();render();toast("Família atualizada")}})}
$("#createFamily").onclick=async()=>{if(!NinhoCloud.enabled)return toast("Conecte a nuvem primeiro");try{let f=await NinhoCloud.createFamily("Minha família");NINHO_FAMILY={id:f.family_id,invite:f.invite_code,plan:"free"};onboarding.classList.add("hide");data=ownerOnlyData();localStorage.setItem(K,JSON.stringify(data));render();await NinhoCloud.saveFamily(NINHO_FAMILY.id,data);NinhoCloud.realtime(NINHO_FAMILY.id,p=>{if(p){data=p;save();render()}});toast("Família criada ✓")}catch(e){toast(e.message)}};$("#joinForm").onsubmit=async e=>{e.preventDefault();try{await NinhoCloud.joinFamily($("#inviteCode").value);onboarding.classList.add("hide");await bootCloud();toast("Você entrou na família ✓")}catch(x){toast(x.message||"Código inválido")}};
const localSave=save;save=()=>{localSave();if(!NINHO_USER.demo&&NINHO_FAMILY.id)NinhoCloud.saveFamily(NINHO_FAMILY.id,data)};const legacyCopyInvite=$("#copyInvite");if(legacyCopyInvite)legacyCopyInvite.onclick=async()=>{await navigator.clipboard?.writeText(NINHO_FAMILY.invite);toast("Código copiado: "+NINHO_FAMILY.invite)};$("#logoutBtn").onclick=async()=>{await NinhoCloud.signOut();location.reload()};
const pbg=$("#premiumBg"),legacyPremiumBtn=$("#premiumBtn");if(legacyPremiumBtn)legacyPremiumBtn.onclick=()=>pbg.classList.add("open");const closePremiumBtn=$("#closePremium");if(closePremiumBtn)closePremiumBtn.onclick=()=>pbg.classList.remove("open");if(pbg)pbg.onclick=e=>{if(e.target===pbg)pbg.classList.remove("open")};const subscribeBtn=$("#subscribeBtn");if(subscribeBtn)subscribeBtn.onclick=()=>toast("Pagamento será conectado na etapa de publicação");
(async()=>{if(!NinhoCloud.enabled)return;try{const s=await NinhoCloud.session();if(s){const p=await NinhoCloud.profile();NINHO_USER={demo:false,name:p?.name||s.user.user_metadata?.name||"Família",email:p?.email||s.user.email,phone:p?.phone||""};authScreen.classList.add("hide");verifyEmailScreen.classList.add("hide");await bootCloud();if(location.hash.includes("access_token")||location.search.includes("code="))toast("E-mail confirmado ✓")}}catch(e){console.error(e)}})();
const detailBg=$("#detailBg");function openDetail(title,content){$("#detailTitle").textContent=title;$("#detailContent").innerHTML=content;detailBg.classList.add("open")}$("#closeDetail").onclick=()=>detailBg.classList.remove("open");detailBg.onclick=e=>{if(e.target===detailBg)detailBg.classList.remove("open")};
function refreshSettings(){const me=data.members[0]||{name:NINHO_USER.name||"Usuário",initial:"U"};$("#settingsName").textContent=NINHO_USER.name||me.name;$("#settingsAvatar").textContent=(NINHO_USER.name||me.name||"U")[0].toUpperCase();$("#settingsEmail").textContent=NINHO_USER.email||"Conta conectada";$("#memberCountLabel").textContent=`${data.members.length} ${data.members.length===1?"membro":"membros"}`;$("#inviteSmall").textContent="Código "+(NINHO_FAMILY.invite||"—");$("#planName").textContent=NINHO_FAMILY.plan==="plus"?"Ninho+":"Ninho gratuito";$("#planStatus").textContent=NINHO_FAMILY.plan==="plus"?"Assinatura ativa":"Conheça os recursos do Ninho+"}
$("#profile").onclick=()=>{refreshSettings();fbg.classList.add("open")};
$("#personalDataBtn").onclick=async()=>{let p=await NinhoCloud.profile();openDetail("Dados pessoais",`<form class="detail-form" id="profileForm"><label>Nome<input name="name" value="${p?.name||NINHO_USER.name||""}" required></label><label>E-mail<input name="email" type="email" value="${p?.email||NINHO_USER.email||""}" required></label><label>Telefone<input name="phone" type="tel" value="${p?.phone||""}" placeholder="(11) 99999-9999"></label><button class="full">Salvar alterações</button></form>`);$("#profileForm").onsubmit=async e=>{e.preventDefault();try{let x=Object.fromEntries(new FormData(e.target));let updated=await NinhoCloud.updateProfile(x);NINHO_USER={...NINHO_USER,...updated};refreshSettings();detailBg.classList.remove("open");toast(x.email!==p.email?"Dados salvos. Novo e-mail pode precisar de confirmação.":"Dados atualizados ✓")}catch(err){toast(err.message||"Erro ao salvar")}}};
$("#editProfileBtn").onclick=()=>$("#personalDataBtn").click();$("#membersBtn").onclick=()=>openDetail("Membros da família",data.members.map(m=>`<div class="member-manage">${av(m)}<div><b>${m.name}</b><small>${m.id===data.members[0]?.id?"Administrador":"Membro"}</small></div></div>`).join("")+`<button class="full" id="detailAddMember">＋ Adicionar membro</button>`);$("#inviteSettingsBtn").onclick=()=>openDetail("Convidar para a família",`<div class="invite-box"><div>Compartilhe este código</div><div class="invite-code">${NINHO_FAMILY.invite||"—"}</div><small>O familiar cria uma conta e usa o código para entrar no seu Ninho.</small></div><button class="full" id="copyInviteDetail">Copiar código</button>`);
$("#subscriptionBtn").onclick=()=>{if(NINHO_FAMILY.plan==="plus")openDetail("Minha assinatura",`<div class="sub-card"><small>PLANO ATUAL</small><h3>💎 Ninho+</h3><p>R$ 12,90/mês · assinatura familiar</p><b>Ativa</b></div><button class="cancel-btn" id="cancelSub">Cancelar assinatura</button>`);else{fbg.classList.remove("open");pbg.classList.add("open")}};
$("#leaveFamilyBtn").onclick=()=>openDetail("Sair da família",`<div class="confirm-box"><p>Ao sair desta família, você deixará de ver a agenda, tarefas e listas compartilhadas. Sua conta continuará existindo.</p><div class="confirm-actions"><button class="safe" id="stayFamily">Ficar</button><button class="danger" id="confirmLeave">Sair da família</button></div></div>`);$("#notificationsBtn").onclick=()=>openDetail("Notificações",`<div class="member-manage"><div>🔔</div><div><b>Lembretes</b><small>Compromissos e tarefas atribuídas a você</small></div><input type="checkbox" checked></div><div class="member-manage"><div>🏡</div><div><b>Atividade da família</b><small>Avisos importantes do Ninho</small></div><input type="checkbox" checked></div>`);
detailBg.addEventListener("click",async e=>{if(e.target.id==="copyInviteDetail"){await navigator.clipboard?.writeText(NINHO_FAMILY.invite||"");toast("Código copiado ✓")}if(e.target.id==="detailAddMember"){detailBg.classList.remove("open");fbg.classList.remove("open");open("member")}if(e.target.id==="stayFamily")detailBg.classList.remove("open");if(e.target.id==="confirmLeave"){detailBg.classList.remove("open");fbg.classList.remove("open");toast("Saída da família preparada para o backend")}if(e.target.id==="cancelSub")openDetail("Cancelar Ninho+",`<div class="confirm-box"><p>Seu Ninho+ continuará ativo até o fim do período já pago. Depois, sua família volta ao plano gratuito.</p><div class="confirm-actions"><button class="safe" id="staySub">Manter Ninho+</button><button class="danger" id="confirmCancel">Cancelar</button></div></div>`);if(e.target.id==="staySub")detailBg.classList.remove("open");if(e.target.id==="confirmCancel"){NINHO_FAMILY.plan="free";detailBg.classList.remove("open");toast("Cancelamento preparado para o sistema de cobrança")}});
