window.NinhoCloud=(()=>{
 const cfg=window.NINHO_CONFIG||{};
 const enabled=!!(cfg.supabaseUrl&&cfg.supabasePublishableKey&&window.supabase);
 const sb=enabled?window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage}}):null;
 let channel=null;
 async function signUp(email,password,name,captchaToken){if(!enabled)throw Error("Nuvem indisponível");const redirectTo=(location.protocol==="http:"||location.protocol==="https:")?(location.origin+location.pathname):undefined;const options={data:{name},captchaToken};if(redirectTo)options.emailRedirectTo=redirectTo;const r=await sb.auth.signUp({email,password,options});if(r.error)throw r.error;if(r.data.session&&r.data.user){const pr=await sb.from("profiles").upsert({id:r.data.user.id,name:name||"",updated_at:new Date().toISOString()});if(pr.error)throw pr.error}return r}
 async function signIn(email,password,captchaToken){const r=await sb.auth.signInWithPassword({email,password,options:{captchaToken}});if(r.error)throw r.error;return r}
 async function resendConfirmation(email,captchaToken){if(!enabled)throw Error("Nuvem indisponível");const redirectTo=(location.protocol==="http:"||location.protocol==="https:")?(location.origin+location.pathname):undefined;const options={captchaToken};if(redirectTo)options.emailRedirectTo=redirectTo;const {error}=await sb.auth.resend({type:"signup",email,options});if(error)throw error;return true}
 async function requestPasswordReset(email,captchaToken){const redirectTo=(location.protocol==="http:"||location.protocol==="https:")?(location.origin+location.pathname):undefined;const options={captchaToken};if(redirectTo)options.redirectTo=redirectTo;const {error}=await sb.auth.resetPasswordForEmail(email,options);if(error)throw error;return true}
 async function updatePassword(password){const {error}=await sb.auth.updateUser({password});if(error)throw error;return true}
 function onAuthChange(cb){return sb.auth.onAuthStateChange((event,session)=>cb(event,session))}
 async function signOut(){return sb.auth.signOut()}
 async function session(){return (await sb.auth.getSession()).data.session}
 async function user(){return (await sb.auth.getUser()).data.user}
 async function profile(){const u=await user();if(!u)return null;let {data,error}=await sb.from("profiles").select("name,phone").eq("id",u.id).maybeSingle();if(error)throw error;if(!data){const name=u.user_metadata?.name||"";const ins=await sb.from("profiles").upsert({id:u.id,name,updated_at:new Date().toISOString()}).select("name,phone").single();if(!ins.error)data=ins.data}return {id:u.id,email:u.email,name:data?.name||u.user_metadata?.name||"",phone:data?.phone||""}}
 async function updateProfile({name,phone,email}){const u=await user();if(!u)throw Error("Sessão expirada");const {error}=await sb.from("profiles").upsert({id:u.id,name:name||"",phone:phone||null,updated_at:new Date().toISOString()});if(error)throw error;if(email&&email!==u.email){const x=await sb.auth.updateUser({email});if(x.error)throw x.error}await sb.auth.updateUser({data:{name:name||""}});return profile()}
 async function loadFamily(){const {data,error}=await sb.rpc("my_family");if(error)throw error;const f=Array.isArray(data)?data[0]:data;if(!f)return null;return {family_id:f.family_id,family_name:f.family_name,invite_code:f.invite_code,plan:f.plan,role:f.role,payload:f.payload}}
 async function familyMembers(){const {data,error}=await sb.rpc("family_members_list");if(error)throw error;return (data||[]).map((m,i)=>({id:m.user_id,name:m.name||"Membro",role:m.role||"adult",initial:(m.name||"M")[0].toUpperCase(),color:["#b9cfb5","#e3b8a6","#b9c9d7","#d9c49a","#d1b8d5"][i%5]}))}
 async function loadShared(familyId){const [t,e,s]=await Promise.all([sb.from("tasks").select("id,title,assignee_id,done,proof_path,proof_by,proof_at").eq("family_id",familyId),sb.from("events").select("id,title,event_date,event_time,assignee_id").eq("family_id",familyId),sb.from("shopping_items").select("id,title,done").eq("family_id",familyId)]);if(t.error)throw t.error;if(e.error)throw e.error;if(s.error)throw s.error;return {tasks:(t.data||[]).map(x=>({id:x.id,title:x.title,member:x.assignee_id,done:x.done,proofPath:x.proof_path||null,proofBy:x.proof_by||null,proofAt:x.proof_at||null})),events:(e.data||[]).map(x=>({id:x.id,title:x.title,date:x.event_date,time:String(x.event_time||"").slice(0,5),member:x.assignee_id})),shopping:(s.data||[]).map(x=>({id:x.id,title:x.title,done:x.done}))}}
 async function addTask(familyId,x){const u=await user();const {error}=await sb.from("tasks").insert({id:x.id,family_id:familyId,title:x.title,assignee_id:x.member||null,done:false,created_by:u.id});if(error)throw error}
 async function setTaskDone(id,done){let proofPath=null;if(!done){const current=await sb.from("tasks").select("proof_path").eq("id",id).maybeSingle();if(current.error)throw current.error;proofPath=current.data?.proof_path||null}const {error}=await sb.rpc("set_task_done",{task_id:id,is_done:done});if(error)throw error;if(!done&&proofPath){const removed=await sb.storage.from("task-proofs").remove([proofPath]);if(removed.error)console.warn("Não foi possível remover comprovante antigo",removed.error)}}
 async function uploadTaskProof(familyId,taskId,file){if(!file)return null;const allowed={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"};const ext=allowed[file.type];if(!ext)throw Error("Use uma foto JPG, PNG ou WebP");if(file.size>5*1024*1024)throw Error("A foto deve ter no máximo 5 MB");const u=await user();if(!u)throw Error("Sessão expirada");const path=`${familyId}/${taskId}/${u.id}-${Date.now()}.${ext}`;const {error}=await sb.storage.from("task-proofs").upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(error)throw error;return path}
 async function completeTask(id,familyId,file){let proofPath=null;try{proofPath=await uploadTaskProof(familyId,id,file);const {error}=await sb.rpc("complete_task_with_proof",{task_id:id,p_proof_path:proofPath});if(error)throw error;return proofPath}catch(err){if(proofPath){try{await sb.storage.from("task-proofs").remove([proofPath])}catch{}}throw err}}
 async function taskProofUrl(path){if(!path)throw Error("Comprovante indisponível");const {data,error}=await sb.storage.from("task-proofs").createSignedUrl(path,300);if(error)throw error;return data?.signedUrl||data?.signedURL}
 async function familyActivity(familyId,limit=50){const {data,error}=await sb.from("family_activity").select("id,family_id,actor_id,action,entity_type,entity_id,title,created_at").eq("family_id",familyId).order("created_at",{ascending:false}).limit(limit);if(error)throw error;return data||[]}
 async function addEvent(familyId,x){const u=await user();const {error}=await sb.from("events").insert({id:x.id,family_id:familyId,title:x.title,event_date:x.date,event_time:x.time,assignee_id:x.member||null,created_by:u.id});if(error)throw error}
 async function addShopping(familyId,x){const u=await user();const {error}=await sb.from("shopping_items").insert({id:x.id,family_id:familyId,title:x.title,done:false,created_by:u.id});if(error)throw error}
 async function setShoppingDone(id,done){const {error}=await sb.rpc("set_shopping_done",{item_id:id,is_done:done});if(error)throw error}
 async function deleteShopping(id){const {error}=await sb.from("shopping_items").delete().eq("id",id);if(error)throw error}
 async function createFamily(name){const {data,error}=await sb.rpc("create_family",{family_name:name});if(error)throw error;return data}
 async function joinFamily(code){const {data,error}=await sb.rpc("join_family",{join_code:code.toUpperCase()});if(error)throw error;return data}
 async function setMemberRole(userId,role){const {error}=await sb.rpc("set_family_member_role",{target_user:userId,new_role:role});if(error)throw error;return true}
 async function removeMember(userId){const {error}=await sb.rpc("remove_family_member",{target_user:userId});if(error)throw error;return true}
 async function transferAdmin(userId){const {error}=await sb.rpc("transfer_family_admin",{target_user:userId});if(error)throw error;return true}
 async function leaveFamily(){const {error}=await sb.rpc("leave_family");if(error)throw error;return true}
 async function deleteAccount(){const {data,error}=await sb.functions.invoke("delete-account",{body:{confirmation:"EXCLUIR"}});if(error){let payload=null;try{payload=await error.context?.json()}catch{}const err=new Error(payload?.error||error.message||"Não foi possível excluir sua conta");if(payload?.code)err.code=payload.code;throw err}if(!data?.ok)throw Error(data?.error||"Não foi possível excluir sua conta");try{await sb.auth.signOut({scope:"local"})}catch{}return true}
 function realtime(familyId,onShared,onMembers,onActivity){if(!familyId)return;if(channel)sb.removeChannel(channel);const refresh=()=>onShared?.();channel=sb.channel("family-"+familyId).on("postgres_changes",{event:"*",schema:"public",table:"tasks",filter:`family_id=eq.${familyId}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"events",filter:`family_id=eq.${familyId}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"shopping_items",filter:`family_id=eq.${familyId}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"family_members",filter:`family_id=eq.${familyId}`},()=>onMembers?.()).on("postgres_changes",{event:"INSERT",schema:"public",table:"family_activity",filter:`family_id=eq.${familyId}`},payload=>onActivity?.(payload.new)).subscribe()}
 
 async function updateContent(kind,id,x){const table={task:"tasks",event:"events",shopping:"shopping_items"}[kind];if(!table)throw Error("Tipo inválido");const patch={title:x.title};if(kind!=="shopping")patch.assignee_id=x.member||null;if(kind==="event"){patch.event_date=x.date;patch.event_time=x.time}const {data,error}=await sb.from(table).update(patch).eq("id",id).select("id");if(error)throw error;if(!data?.length)throw Error("Item indisponível ou sem permissão")}
 async function deleteContent(kind,id){const table={task:"tasks",event:"events",shopping:"shopping_items"}[kind];if(!table)throw Error("Tipo inválido");let proofPath=null;if(kind==="task"){const current=await sb.from("tasks").select("proof_path").eq("id",id).maybeSingle();if(current.error)throw current.error;proofPath=current.data?.proof_path||null}const {data,error}=await sb.from(table).delete().eq("id",id).select("id");if(error)throw error;if(!data?.length)throw Error("Item indisponível ou sem permissão");if(proofPath){const removed=await sb.storage.from("task-proofs").remove([proofPath]);if(removed.error)console.warn("Não foi possível remover comprovante da tarefa",removed.error)}}

 return {updateContent,deleteContent,enabled,sb,signUp,signIn,resendConfirmation,requestPasswordReset,updatePassword,onAuthChange,signOut,session,user,profile,updateProfile,loadFamily,familyMembers,loadShared,addTask,setTaskDone,completeTask,taskProofUrl,familyActivity,addEvent,addShopping,setShoppingDone,deleteShopping,createFamily,joinFamily,setMemberRole,removeMember,transferAdmin,leaveFamily,deleteAccount,realtime};
})();