const test=require('node:test');const assert=require('node:assert/strict');
const load=()=>import('../supabase/functions/close-family/handler.mjs');
const family='12345678-1234-1234-1234-123456789abc';
const req=(body={familyId:family,confirmation:'ENCERRAR'},token='token')=>new Request('https://qa.invalid',{method:'POST',headers:token?{authorization:'Bearer '+token}:{},body:JSON.stringify(body)});
function mock({closeError=null,removeError=null,paths=[family+'/task/photo.jpg']}={}){const calls=[];return{calls,admin:{auth:{getUser:async()=>({data:{user:{id:'u'}}})},rpc:async(name,args)=>{calls.push([name,args]);return{data:paths}},storage:{from:()=>({remove:async paths=>{calls.push(['remove',paths]);return{error:removeError}}})}},forUser:()=>({rpc:async()=>{calls.push(['close']);return{error:closeError}}})};}
test('requires authenticated request and explicit confirmation',async()=>{const {createCloseHandler}=await load();const m=mock();const h=createCloseHandler(m.admin,m.forUser);assert.equal((await h(req({},null))).status,401);assert.equal((await h(req({familyId:family,confirmation:'yes'}))).status,400);assert.equal(m.calls.length,0);});
test('rejected family closure never deletes files',async()=>{const {createCloseHandler}=await load();const m=mock({closeError:{message:'Other members'}});assert.equal((await createCloseHandler(m.admin,m.forUser)(req())).status,409);assert.ok(!m.calls.some(c=>c[0]==='remove'));});
test('storage failure preserves pending cleanup and reports account preserved',async()=>{const {createCloseHandler}=await load();const m=mock({removeError:{message:'retry'}});const r=await createCloseHandler(m.admin,m.forUser)(req());assert.deepEqual(await r.json(),{ok:true,cleanupPending:true});assert.ok(!m.calls.some(c=>c[1]?.p_complete===true));});
test('only closed-family files can be removed',async()=>{const {createCloseHandler}=await load();const m=mock({paths:['another-family/photo.jpg']});const r=await createCloseHandler(m.admin,m.forUser)(req());assert.equal((await r.json()).cleanupPending,true);assert.ok(!m.calls.some(c=>c[0]==='remove'));});
test('successful closure deletes files before marking cleanup complete',async()=>{const {createCloseHandler}=await load();const m=mock();const r=await createCloseHandler(m.admin,m.forUser)(req());assert.deepEqual(await r.json(),{ok:true,cleanupPending:false});assert.ok(m.calls.findIndex(c=>c[0]==='remove')<m.calls.findIndex(c=>c[1]?.p_complete===true));});
